# Generated by Django 4.1.3 on 2022-12-12 10:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teams', '0002_alter_teams_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('stadium', models.CharField(max_length=80)),
                ('goal_home_team', models.PositiveSmallIntegerField()),
                ('goal_away_team', models.PositiveSmallIntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='Teams.teams')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='Teams.teams')),
            ],
        ),
    ]
