# Generated by Django 4.1.4 on 2022-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='goal_away_team',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='goal_home_team',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
