# Generated by Django 4.1.3 on 2022-12-06 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group', models.CharField(choices=[('A', 'Groupe A'), ('B', 'Groupe B'), ('C', 'Groupe C'), ('D', 'Groupe D'), ('E', 'Groupe F'), ('E', 'Groupe F'), ('G', 'Groupe G'), ('H', 'Groupe EH')], max_length=1)),
                ('is_eliminated', models.BooleanField(default=True)),
            ],
        ),
    ]
