# Generated by Django 4.1.3 on 2022-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='group',
            field=models.CharField(choices=[('A', 'Groupe A'), ('B', 'Groupe B'), ('C', 'Groupe C'), ('D', 'Groupe D'), ('E', 'Groupe F'), ('F', 'Groupe F'), ('G', 'Groupe G'), ('H', 'Groupe EH')], max_length=1),
        ),
    ]
