# Generated by Django 4.1.4 on 2022-12-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_alter_teams_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1),
        ),
    ]
